name: sound_stream
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://tomas.radvansky.org

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.10.5'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  plugin:
    platforms:
      android:
        package: nz.co.rdev.sound_stream
        pluginClass: SoundStreamPlugin
      ios:
        pluginClass: SoundStreamPlugin
